### ISSUE TITLE
Sometimes entering the help/inventory menu will result in a softlock. This seems to be random

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#49]

**Comment by ProjectEranOrel** [comment]
I've encountered the same problem

**Comment by ShadowOfNight** [comment]
This appears to be a problem in the alpha build's help menu as well.

**Comment by Vahkiti** [comment]
Fixed as of REBUILT 1.1 and Beta 1.5

**Comment by fhuewhd** [comment]
I'm still getting this error, or else it's a different inventory error.  I'm using the "Rebuilt" version, downloaded from the website recently.  When I select "inventory", the inventory doesn't appear and the game freezes.  

It also apparently chewed up my save file - the next time I opened the game, the count for the little silver tokens was back to 0, I was in Whenua's hut for some reason (having previously been in a cave, I think) and it had gone back to the battle with the Rahi in the village, which I'd already done.  

I haven't tried to replicate this again in case it chews up my save file again!  Are the two files labelled ".sav" the complete save file - will making copies of those and replacing them with those enable me to restore the save file completely if it goes wrong again?

**Comment by Vahkiti** [comment]
The save file issue is unrelated. We thought we'd fixed it in the latest hotfix, but something seems to not be quite right and requires further investigtion. This inventory issue however is as previously mentioned, set to be fixed in the next REBUILT version due to basically being recoded from the ground up. Legacy will also recieve these changes.

**Comment by fhuewhd** [comment]
Oh, the _next_ "Rebuilt" version, I see.  Thanks!
